/* Generated by gbrecomp from Yu-Gi-Oh! Dark Duel Stories (U) [C][!] */
#include "Yu_Gi_Oh__Dark_Duel_Stories__U___C_____internal.h"

/* Shared body at 0c:40a7 */
static void body_0c_40a7(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x40a7: goto loc_0c_40a7;
        case 0x40a8: goto loc_0c_40a8;
        case 0x40a9: goto pc_40a9;
        case 0x40aa: goto pc_40aa;
        case 0x40ab: goto pc_40ab;
        case 0x40ac: goto pc_40ac;
        case 0x40ad: goto pc_40ad;
        case 0x40ae: goto pc_40ae;
        case 0x40af: goto pc_40af;
        case 0x40b0: goto pc_40b0;
        case 0x40b1: goto pc_40b1;
        case 0x40b2: goto pc_40b2;
        case 0x40b3: goto pc_40b3;
        case 0x40b4: goto pc_40b4;
        case 0x40b5: goto pc_40b5;
        case 0x40b6: goto pc_40b6;
        case 0x40b7: goto pc_40b7;
        case 0x40b8: goto pc_40b8;
        default: break;
    }

loc_0c_40a7:
    /* RET Z */
    /* 0c:40a7 */     if (ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* Z */
    gbrt_timed_jump(ctx, 0x40a8, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0c_40a8:
    /* LD D,D */
    /* 0c:40a8 */     ctx->d = ctx->d;
    ctx->pc = 0x40a9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,L */
pc_40a9:
    /* 0c:40a9 */     ctx->d = ctx->l;
    ctx->pc = 0x40aa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,E */
pc_40aa:
    /* 0c:40aa */     ctx->d = ctx->e;
    ctx->pc = 0x40ab;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH (C),A */
pc_40ab:
    /* 0c:40ab */     gb_tick(ctx, 7);
    gb_write8(ctx, GB_IO_BASE + ctx->c, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x40ac;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,E */
pc_40ac:
    /* 0c:40ac */     ctx->d = ctx->e;
    ctx->pc = 0x40ad;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_40ad:
    /* 0c:40ad */     ctx->l = ctx->a;
    ctx->pc = 0x40ae;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,H */
pc_40ae:
    /* 0c:40ae */     ctx->d = ctx->h;
    ctx->pc = 0x40af;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_40af:
    /* 0c:40af */     /* NOP */
    ctx->pc = 0x40b0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,L */
pc_40b0:
    /* 0c:40b0 */     ctx->d = ctx->l;
    ctx->pc = 0x40b1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB C */
pc_40b1:
    /* 0c:40b1 */     gb_sub8(ctx, ctx->c);
    ctx->pc = 0x40b2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,L */
pc_40b2:
    /* 0c:40b2 */     ctx->d = ctx->l;
    ctx->pc = 0x40b3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
pc_40b3:
    /* 0c:40b3 */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x40b4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,(HL) */
pc_40b4:
    /* 0c:40b4 */     gb_tick(ctx, 7);
    ctx->d = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x40b5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP E */
pc_40b5:
    /* 0c:40b5 */     gb_cp8(ctx, ctx->e);
    ctx->pc = 0x40b6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,(HL) */
pc_40b6:
    /* 0c:40b6 */     gb_tick(ctx, 7);
    ctx->d = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x40b7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,H */
pc_40b7:
    /* 0c:40b7 */     ctx->d = ctx->h;
    ctx->pc = 0x40b8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,A */
pc_40b8:
    /* 0c:40b8 */     ctx->d = ctx->a;
    ctx->pc = 0x40b9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x40b9 in bank 12 */
    return;
}

void func_0c_40a7(GBContext* ctx) {
    body_0c_40a7(ctx);
}

