/* Generated by gbrecomp from Yu-Gi-Oh! Dark Duel Stories (U) [C][!] */
#include "Yu_Gi_Oh__Dark_Duel_Stories__U___C_____internal.h"

/* Shared body at 06:6238 */
static void body_06_6238(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x622d: goto loc_06_622d;
        case 0x622f: goto pc_622f;
        case 0x6230: goto pc_6230;
        case 0x6231: goto pc_6231;
        case 0x6232: goto pc_6232;
        case 0x6233: goto pc_6233;
        case 0x6234: goto pc_6234;
        case 0x6235: goto pc_6235;
        case 0x6236: goto pc_6236;
        case 0x6237: goto pc_6237;
        case 0x6238: goto loc_06_6238;
        case 0x6239: goto pc_6239;
        case 0x623b: goto pc_623b;
        case 0x623c: goto pc_623c;
        case 0x623d: goto pc_623d;
        case 0x623e: goto loc_06_623e;
        case 0x623f: goto pc_623f;
        case 0x6240: goto pc_6240;
        case 0x6241: goto loc_06_6241;
        case 0x6242: goto loc_06_6242;
        case 0x6243: goto loc_06_6243;
        case 0x6261: goto loc_06_6261;
        case 0x6262: goto loc_06_6262;
        case 0x6263: goto loc_06_6263;
        case 0x6264: goto loc_06_6264;
        case 0x6265: goto loc_06_6265;
        case 0x6266: goto loc_06_6266;
        case 0x6267: goto loc_06_6267;
        case 0x6268: goto loc_06_6268;
        case 0x626a: goto loc_06_626a;
        case 0x626c: goto loc_06_626c;
        case 0x626d: goto pc_626d;
        case 0x626f: goto pc_626f;
        case 0x6270: goto pc_6270;
        case 0x6273: goto pc_6273;
        case 0x6276: goto pc_6276;
        case 0x6277: goto pc_6277;
        case 0x627a: goto pc_627a;
        case 0x627b: goto pc_627b;
        case 0x627d: goto pc_627d;
        case 0x627e: goto pc_627e;
        case 0x627f: goto pc_627f;
        case 0x6280: goto loc_06_6280;
        case 0x6281: goto pc_6281;
        case 0x6282: goto pc_6282;
        case 0x6283: goto pc_6283;
        case 0x6284: goto pc_6284;
        case 0x6285: goto loc_06_6285;
        case 0x6288: goto pc_6288;
        case 0x6289: goto pc_6289;
        case 0x628a: goto pc_628a;
        case 0x628b: goto pc_628b;
        case 0x628c: goto pc_628c;
        case 0x628d: goto pc_628d;
        case 0x628f: goto loc_06_628f;
        case 0x6290: goto pc_6290;
        case 0x6291: goto pc_6291;
        case 0x6292: goto pc_6292;
        default: break;
    }

loc_06_622d:
    /* CP $80 */
    /* 06:622d */     gb_cp8(ctx, 0x80);
    ctx->pc = 0x622f;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,B */
pc_622f:
    /* 06:622f */     ctx->b = ctx->b;
    if (gbrt_test_breakpoint_enabled) {
        ctx->pc = 0x6230;
        ctx->stopped = 1;
        return;
    }
    ctx->pc = 0x6230;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB L */
pc_6230:
    /* 06:6230 */     gb_sub8(ctx, ctx->l);
    ctx->pc = 0x6231;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,D */
pc_6231:
    /* 06:6231 */     ctx->l = ctx->d;
    ctx->pc = 0x6232;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(BC) */
pc_6232:
    /* 06:6232 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->bc);
    gb_tick(ctx, 1);
    ctx->pc = 0x6233;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL+) */
pc_6233:
    /* 06:6233 */     ctx->a = gbrt_timed_hl_read_auto(ctx, 1);
    ctx->pc = 0x6234;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,E */
pc_6234:
    /* 06:6234 */     gb_adc8(ctx, ctx->e);
    ctx->pc = 0x6235;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL+) */
pc_6235:
    /* 06:6235 */     ctx->a = gbrt_timed_hl_read_auto(ctx, 1);
    ctx->pc = 0x6236;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_6236:
    /* 06:6236 */     gb_rrca(ctx);
    ctx->pc = 0x6237;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR E */
pc_6237:
    /* 06:6237 */     gb_xor8(ctx, ctx->e);
    ctx->pc = 0x6238;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_6238:
    /* LD C,A */
    /* 06:6238 */     ctx->c = ctx->a;
    ctx->pc = 0x6239;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$0f */
pc_6239:
    /* 06:6239 */     ctx->e = 0x0f;
    ctx->pc = 0x623b;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,A */
pc_623b:
    /* 06:623b */     gb_sbc8(ctx, ctx->a);
    ctx->pc = 0x623c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,A */
pc_623c:
    /* 06:623c */     ctx->a = ctx->a;
    ctx->pc = 0x623d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $18 */
pc_623d:
    /* 06:623d */     gbrt_timed_rst(ctx, 0x18, 0x623e);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_18(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_623e:
    /* RRA */
    /* 06:623e */     gb_rra(ctx);
    ctx->pc = 0x623f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,A */
pc_623f:
    /* 06:623f */     ctx->a = ctx->a;
    ctx->pc = 0x6240;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_6240:
    /* 06:6240 */     gbrt_timed_rst(ctx, 0x38, 0x6241);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6241:
    /* RST $38 */
    /* 06:6241 */     gbrt_timed_rst(ctx, 0x38, 0x6242);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6242:
    /* RST $38 */
    /* 06:6242 */     gbrt_timed_rst(ctx, 0x38, 0x6243);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6243:
    /* CP A */
    /* 06:6243 */     gb_cp8(ctx, ctx->a);
    ctx->pc = 0x6244;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x6244 in bank 6 */
    return;
loc_06_6261:
    /* RET Z */
    /* 06:6261 */     if (ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* Z */
    gbrt_timed_jump(ctx, 0x6262, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_6262:
    /* RET C */
    /* 06:6262 */     if (ctx->f_c) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* C */
    gbrt_timed_jump(ctx, 0x6263, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_6263:
    /* RET NZ */
    /* 06:6263 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x6264, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_6264:
    /* RET NZ */
    /* 06:6264 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x6265, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_6265:
    /* RET NZ */
    /* 06:6265 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x6266, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_6266:
    /* RET NZ */
    /* 06:6266 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x6267, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_6267:
    /* RET NZ */
    /* 06:6267 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x6268, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_6268:
    /* JR NZ,0 */
    /* 06:6268 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x626a, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_06_626a;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x626a, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_626a:
    /* LD BC,$0800 */
    /* 06:626a */     ctx->bc = 0x0800;
    ctx->pc = 0x626d;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0900 */
pc_626d:
    /* 06:626d */     ctx->bc = 0x0900;
    ctx->pc = 0x6270;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0400 */
pc_6270:
    /* 06:6270 */     ctx->bc = 0x0400;
    ctx->pc = 0x6273;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($0f11),SP */
pc_6273:
    /* 06:6273 */     gb_write16(ctx, 0x0f11, ctx->sp);
    ctx->pc = 0x6276;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_6276:
    /* 06:6276 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x6277;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($1024),SP */
pc_6277:
    /* 06:6277 */     gb_write16(ctx, 0x1024, ctx->sp);
    ctx->pc = 0x627a;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC H */
pc_627a:
    /* 06:627a */     ctx->h = gb_inc8(ctx, ctx->h);
    ctx->pc = 0x627b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* STOP */
pc_627b:
    /* 06:627b */     ctx->pc = 0x627d;
    gb_stop(ctx);
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_627d:
    /* 06:627d */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x627e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
pc_627e:
    /* 06:627e */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x627f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_627f:
    /* 06:627f */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x6280;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_06_6280; /* fallthrough */
loc_06_626c:
    /* LD ($0001),SP */
    /* 06:626c */     gb_write16(ctx, 0x0001, ctx->sp);
    ctx->pc = 0x626f;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,BC */
pc_626f:
    /* 06:626f */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x6270;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0400 */
    /* 06:6270 */     ctx->bc = 0x0400;
    ctx->pc = 0x6273;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($0f11),SP */
    /* 06:6273 */     gb_write16(ctx, 0x0f11, ctx->sp);
    ctx->pc = 0x6276;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
    /* 06:6276 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x6277;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($1024),SP */
    /* 06:6277 */     gb_write16(ctx, 0x1024, ctx->sp);
    ctx->pc = 0x627a;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC H */
    /* 06:627a */     ctx->h = gb_inc8(ctx, ctx->h);
    ctx->pc = 0x627b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* STOP */
    /* 06:627b */     ctx->pc = 0x627d;
    gb_stop(ctx);
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* INC D */
    /* 06:627d */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x627e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
    /* 06:627e */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x627f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
    /* 06:627f */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x6280;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_6280:
    /* LD (BC),A */
    /* 06:6280 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x6281;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_6281:
    /* 06:6281 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x6282;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC C */
pc_6282:
    /* 06:6282 */     ctx->c = gb_inc8(ctx, ctx->c);
    ctx->pc = 0x6283;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_6283:
    /* 06:6283 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x6284;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NZ */
pc_6284:
    /* 06:6284 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x6285, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_6285:
    /* LD A,($1a20) */
    /* 06:6285 */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, 0x1a20);
    gb_tick(ctx, 1);
    ctx->pc = 0x6288;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_6288:
    /* 06:6288 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x6289;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6289:
    /* 06:6289 */     /* NOP */
    ctx->pc = 0x628a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL+) */
pc_628a:
    /* 06:628a */     ctx->a = gbrt_timed_hl_read_auto(ctx, 1);
    ctx->pc = 0x628b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_628b:
    /* 06:628b */     /* NOP */
    ctx->pc = 0x628c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,L */
pc_628c:
    /* 06:628c */     gb_add8(ctx, ctx->l);
    ctx->pc = 0x628d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,0 */
pc_628d:
    /* 06:628d */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x628f, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_06_628f;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x628f, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_628f:
    /* AND D */
    /* 06:628f */     gb_and8(ctx, ctx->d);
    ctx->pc = 0x6290;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6290:
    /* 06:6290 */     /* NOP */
    ctx->pc = 0x6291;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_6291:
    /* 06:6291 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x6292;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR -103 */
pc_6292:
    /* 06:6292 */     gbrt_timed_jump(ctx, 0x622d, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_06_622d;
    if (ctx->single_step_mode) return;
}

void func_06_6238(GBContext* ctx) {
    body_06_6238(ctx);
}

void func_06_6261(GBContext* ctx) {
    body_06_6238(ctx);
}

void func_06_626c(GBContext* ctx) {
    body_06_6238(ctx);
}

void func_06_6280(GBContext* ctx) {
    body_06_6238(ctx);
}

/* Shared body at 06:6245 */
static void body_06_6245(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x6245: goto loc_06_6245;
        case 0x6246: goto loc_06_6246;
        default: break;
    }

loc_06_6245:
    /* RST $38 */
    /* 06:6245 */     gbrt_timed_rst(ctx, 0x38, 0x6246);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6246:
    goto loc_06_6246; /* fallthrough */
}

void func_06_6245(GBContext* ctx) {
    body_06_6245(ctx);
}

/* Shared body at 06:624d */
static void body_06_624d(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x624d: goto loc_06_624d;
        case 0x624e: goto loc_06_624e;
        case 0x624f: goto pc_624f;
        case 0x6250: goto pc_6250;
        case 0x6251: goto loc_06_6251;
        case 0x6252: goto loc_06_6252;
        case 0x6253: goto loc_06_6253;
        case 0x6254: goto loc_06_6254;
        case 0x6255: goto loc_06_6255;
        case 0x6256: goto loc_06_6256;
        case 0x6257: goto loc_06_6257;
        case 0x6258: goto loc_06_6258;
        default: break;
    }

loc_06_624d:
    /* RST $38 */
    /* 06:624d */     gbrt_timed_rst(ctx, 0x38, 0x624e);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_624e:
    /* NOP */
    /* 06:624e */     /* NOP */
    ctx->pc = 0x624f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_624f:
    /* 06:624f */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x6250;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$ffff */
pc_6250:
    /* 06:6250 */     ctx->bc = GB_IO_IE;
    ctx->pc = 0x6253;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_06_6253; /* fallthrough */
loc_06_6251:
    /* RST $38 */
    /* 06:6251 */     gbrt_timed_rst(ctx, 0x38, 0x6252);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6252:
    /* RST $38 */
    /* 06:6252 */     gbrt_timed_rst(ctx, 0x38, 0x6253);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6253:
    /* RST $38 */
    /* 06:6253 */     gbrt_timed_rst(ctx, 0x38, 0x6254);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6254:
    /* RST $38 */
    /* 06:6254 */     gbrt_timed_rst(ctx, 0x38, 0x6255);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6255:
    /* RST $38 */
    /* 06:6255 */     gbrt_timed_rst(ctx, 0x38, 0x6256);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6256:
    /* RST $38 */
    /* 06:6256 */     gbrt_timed_rst(ctx, 0x38, 0x6257);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6257:
    /* RST $38 */
    /* 06:6257 */     gbrt_timed_rst(ctx, 0x38, 0x6258);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6258:
    goto loc_06_6258; /* fallthrough */
}

void func_06_624d(GBContext* ctx) {
    body_06_624d(ctx);
}

void func_06_6251(GBContext* ctx) {
    body_06_624d(ctx);
}

/* Shared body at 06:6296 */
static void body_06_6296(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x6296: goto loc_06_6296;
        case 0x6297: goto pc_6297;
        case 0x6298: goto loc_06_6298;
        case 0x6299: goto pc_6299;
        case 0x629c: goto pc_629c;
        case 0x629f: goto pc_629f;
        case 0x62a0: goto pc_62a0;
        case 0x62a2: goto loc_06_62a2;
        case 0x62a3: goto pc_62a3;
        case 0x62a4: goto pc_62a4;
        case 0x62a5: goto pc_62a5;
        case 0x62a7: goto pc_62a7;
        case 0x62a8: goto pc_62a8;
        case 0x62a9: goto pc_62a9;
        case 0x62aa: goto loc_06_62aa;
        case 0x62ab: goto pc_62ab;
        case 0x62ac: goto loc_06_62ac;
        case 0x62ad: goto pc_62ad;
        case 0x62ae: goto loc_06_62ae;
        case 0x62af: goto pc_62af;
        case 0x62b0: goto loc_06_62b0;
        case 0x62b1: goto pc_62b1;
        case 0x62b2: goto pc_62b2;
        case 0x62b3: goto pc_62b3;
        case 0x62b4: goto pc_62b4;
        case 0x62b5: goto pc_62b5;
        case 0x62b6: goto pc_62b6;
        case 0x62b7: goto pc_62b7;
        case 0x62b8: goto pc_62b8;
        case 0x62b9: goto loc_06_62b9;
        case 0x62ba: goto loc_06_62ba;
        case 0x62bc: goto pc_62bc;
        case 0x62e2: goto loc_06_62e2;
        case 0x62e3: goto pc_62e3;
        case 0x62e4: goto pc_62e4;
        case 0x62e5: goto pc_62e5;
        case 0x62e6: goto pc_62e6;
        case 0x62e7: goto pc_62e7;
        case 0x62e8: goto pc_62e8;
        case 0x62e9: goto pc_62e9;
        case 0x62ea: goto pc_62ea;
        case 0x62eb: goto pc_62eb;
        case 0x62ec: goto pc_62ec;
        case 0x62ed: goto pc_62ed;
        case 0x62ee: goto pc_62ee;
        case 0x62ef: goto pc_62ef;
        case 0x62f0: goto pc_62f0;
        case 0x62f1: goto loc_06_62f1;
        case 0x62f2: goto pc_62f2;
        case 0x62f3: goto loc_06_62f3;
        case 0x62f4: goto pc_62f4;
        case 0x62f6: goto pc_62f6;
        case 0x62f7: goto pc_62f7;
        case 0x62f8: goto pc_62f8;
        case 0x62f9: goto loc_06_62f9;
        case 0x62fa: goto pc_62fa;
        case 0x62fb: goto loc_06_62fb;
        case 0x62fc: goto pc_62fc;
        case 0x62fd: goto pc_62fd;
        case 0x62fe: goto pc_62fe;
        case 0x62ff: goto pc_62ff;
        case 0x6300: goto pc_6300;
        case 0x6301: goto pc_6301;
        case 0x6302: goto pc_6302;
        case 0x6303: goto pc_6303;
        case 0x6304: goto pc_6304;
        case 0x6305: goto pc_6305;
        case 0x6306: goto pc_6306;
        case 0x6307: goto pc_6307;
        case 0x6308: goto pc_6308;
        case 0x630a: goto pc_630a;
        case 0x630b: goto pc_630b;
        case 0x630c: goto pc_630c;
        case 0x630d: goto pc_630d;
        case 0x630e: goto pc_630e;
        case 0x630f: goto pc_630f;
        case 0x6310: goto pc_6310;
        case 0x6311: goto pc_6311;
        case 0x6312: goto pc_6312;
        case 0x6313: goto pc_6313;
        case 0x6314: goto pc_6314;
        case 0x6315: goto pc_6315;
        case 0x6316: goto pc_6316;
        case 0x6317: goto pc_6317;
        case 0x6318: goto pc_6318;
        case 0x6319: goto pc_6319;
        case 0x631a: goto pc_631a;
        case 0x631b: goto pc_631b;
        case 0x631c: goto pc_631c;
        case 0x631f: goto pc_631f;
        case 0x6320: goto pc_6320;
        case 0x6321: goto loc_06_6321;
        case 0x6322: goto pc_6322;
        case 0x6323: goto pc_6323;
        case 0x6324: goto pc_6324;
        case 0x6325: goto pc_6325;
        case 0x6326: goto pc_6326;
        case 0x6327: goto pc_6327;
        case 0x6328: goto pc_6328;
        case 0x6329: goto pc_6329;
        case 0x632a: goto pc_632a;
        case 0x632b: goto pc_632b;
        case 0x632c: goto pc_632c;
        case 0x632d: goto loc_06_632d;
        case 0x632e: goto pc_632e;
        case 0x632f: goto loc_06_632f;
        case 0x6330: goto pc_6330;
        case 0x6331: goto loc_06_6331;
        case 0x6332: goto pc_6332;
        case 0x6333: goto loc_06_6333;
        case 0x6334: goto pc_6334;
        case 0x6336: goto pc_6336;
        case 0x6337: goto pc_6337;
        case 0x6338: goto pc_6338;
        case 0x6339: goto pc_6339;
        case 0x633a: goto pc_633a;
        case 0x633b: goto pc_633b;
        case 0x633c: goto pc_633c;
        case 0x633f: goto pc_633f;
        case 0x6340: goto pc_6340;
        case 0x6341: goto pc_6341;
        case 0x6344: goto pc_6344;
        case 0x6347: goto pc_6347;
        case 0x6348: goto pc_6348;
        case 0x634a: goto loc_06_634a;
        case 0x634b: goto loc_06_634b;
        case 0x634c: goto pc_634c;
        case 0x634d: goto pc_634d;
        case 0x634f: goto pc_634f;
        case 0x6350: goto pc_6350;
        case 0x6351: goto pc_6351;
        case 0x6352: goto pc_6352;
        case 0x6353: goto loc_06_6353;
        case 0x6354: goto pc_6354;
        case 0x6355: goto pc_6355;
        case 0x6356: goto pc_6356;
        case 0x6357: goto pc_6357;
        case 0x6358: goto pc_6358;
        case 0x6359: goto loc_06_6359;
        case 0x635a: goto pc_635a;
        case 0x635b: goto pc_635b;
        case 0x635c: goto loc_06_635c;
        case 0x635d: goto pc_635d;
        case 0x635e: goto loc_06_635e;
        case 0x635f: goto pc_635f;
        case 0x6360: goto pc_6360;
        case 0x6361: goto pc_6361;
        case 0x6362: goto pc_6362;
        case 0x6363: goto pc_6363;
        default: break;
    }

loc_06_6296:
    /* LD H,A */
    /* 06:6296 */     ctx->h = ctx->a;
    ctx->pc = 0x6297;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $08 */
pc_6297:
    /* 06:6297 */     gbrt_timed_rst(ctx, 0x8, 0x6298);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_08(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6298:
    /* INC C */
    /* 06:6298 */     ctx->c = gb_inc8(ctx, ctx->c);
    ctx->pc = 0x6299;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0104 */
pc_6299:
    /* 06:6299 */     ctx->bc = 0x0104;
    ctx->pc = 0x629c;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$8100 */
pc_629c:
    /* 06:629c */     ctx->bc = GB_VRAM_BASE + 0x0100;
    ctx->pc = 0x629f;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_629f:
    /* 06:629f */     /* NOP */
    ctx->pc = 0x62a0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,64 */
pc_62a0:
    /* 06:62a0 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x62e2, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_06_62e2;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x62a2, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_62a2:
    /* AND B */
    /* 06:62a2 */     gb_and8(ctx, ctx->b);
    ctx->pc = 0x62a3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62a3:
    /* 06:62a3 */     /* NOP */
    ctx->pc = 0x62a4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_62a4:
    /* 06:62a4 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x62a5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH ($FF00+$a0),A */
pc_62a5:
    /* 06:62a5 */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_HRAM_BASE + 0x20, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x62a7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,B */
pc_62a7:
    /* 06:62a7 */     ctx->h = ctx->b;
    ctx->pc = 0x62a8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC DE */
pc_62a8:
    /* 06:62a8 */     gbrt_timed_dec16(ctx, &ctx->de);
    ctx->pc = 0x62a9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_62a9:
    /* 06:62a9 */     gbrt_timed_rst(ctx, 0x38, 0x62aa);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_62aa:
    /* CCF */
    /* 06:62aa */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x62ab;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_62ab:
    /* 06:62ab */     gbrt_timed_rst(ctx, 0x38, 0x62ac);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_62ac:
    /* CCF */
    /* 06:62ac */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x62ad;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $28 */
pc_62ad:
    /* 06:62ad */     gbrt_timed_rst(ctx, 0x28, 0x62ae);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_28(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_62ae:
    /* DEC HL */
    /* 06:62ae */     gbrt_timed_dec16(ctx, &ctx->hl);
    ctx->pc = 0x62af;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $28 */
pc_62af:
    /* 06:62af */     gbrt_timed_rst(ctx, 0x28, 0x62b0);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_28(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_62b0:
    /* ADC A,E */
    /* 06:62b0 */     gb_adc8(ctx, ctx->e);
    ctx->pc = 0x62b1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,E */
pc_62b1:
    /* 06:62b1 */     ctx->l = ctx->e;
    ctx->pc = 0x62b2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,E */
pc_62b2:
    /* 06:62b2 */     ctx->b = ctx->e;
    ctx->pc = 0x62b3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_62b3:
    /* 06:62b3 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x62b4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,A */
pc_62b4:
    /* 06:62b4 */     gb_adc8(ctx, ctx->a);
    ctx->pc = 0x62b5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRA */
pc_62b5:
    /* 06:62b5 */     gb_rra(ctx);
    ctx->pc = 0x62b6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC HL */
pc_62b6:
    /* 06:62b6 */     gbrt_timed_dec16(ctx, &ctx->hl);
    ctx->pc = 0x62b7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,A */
pc_62b7:
    /* 06:62b7 */     ctx->b = ctx->a;
    ctx->pc = 0x62b8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $00 */
pc_62b8:
    /* 06:62b8 */     gbrt_timed_rst(ctx, 0x0, 0x62b9);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_00(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_62b9:
    /* RET NZ */
    /* 06:62b9 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x62ba, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_62ba:
    /* RES n,r */
    /* 06:62ba */     ctx->b &= ~(1 << 0);
    ctx->pc = 0x62bc;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_62bc:
    /* 06:62bc */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_62e2:
    /* RRCA */
    /* 06:62e2 */     gb_rrca(ctx);
    ctx->pc = 0x62e3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62e3:
    /* 06:62e3 */     /* NOP */
    ctx->pc = 0x62e4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62e4:
    /* 06:62e4 */     /* NOP */
    ctx->pc = 0x62e5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62e5:
    /* 06:62e5 */     /* NOP */
    ctx->pc = 0x62e6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62e6:
    /* 06:62e6 */     /* NOP */
    ctx->pc = 0x62e7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62e7:
    /* 06:62e7 */     /* NOP */
    ctx->pc = 0x62e8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_62e8:
    /* 06:62e8 */     gb_rrca(ctx);
    ctx->pc = 0x62e9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62e9:
    /* 06:62e9 */     /* NOP */
    ctx->pc = 0x62ea;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_62ea:
    /* 06:62ea */     gb_rrca(ctx);
    ctx->pc = 0x62eb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62eb:
    /* 06:62eb */     /* NOP */
    ctx->pc = 0x62ec;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,A */
pc_62ec:
    /* 06:62ec */     gb_sbc8(ctx, ctx->a);
    ctx->pc = 0x62ed;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62ed:
    /* 06:62ed */     /* NOP */
    ctx->pc = 0x62ee;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,A */
pc_62ee:
    /* 06:62ee */     gb_sbc8(ctx, ctx->a);
    ctx->pc = 0x62ef;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62ef:
    /* 06:62ef */     /* NOP */
    ctx->pc = 0x62f0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_62f0:
    /* 06:62f0 */     gbrt_timed_rst(ctx, 0x38, 0x62f1);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_62f1:
    /* NOP */
    /* 06:62f1 */     /* NOP */
    ctx->pc = 0x62f2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_62f2:
    /* 06:62f2 */     gbrt_timed_rst(ctx, 0x38, 0x62f3);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_62f3:
    /* NOP */
    /* 06:62f3 */     /* NOP */
    ctx->pc = 0x62f4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $00 */
pc_62f4:
    /* 06:62f4 */     gb_cp8(ctx, 0x00);
    ctx->pc = 0x62f6;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC E */
pc_62f6:
    /* 06:62f6 */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x62f7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62f7:
    /* 06:62f7 */     /* NOP */
    ctx->pc = 0x62f8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NZ */
pc_62f8:
    /* 06:62f8 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x62f9, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_62f9:
    /* NOP */
    /* 06:62f9 */     /* NOP */
    ctx->pc = 0x62fa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NZ */
pc_62fa:
    /* 06:62fa */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x62fb, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_62fb:
    /* NOP */
    /* 06:62fb */     /* NOP */
    ctx->pc = 0x62fc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_62fc:
    /* 06:62fc */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x62fd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62fd:
    /* 06:62fd */     /* NOP */
    ctx->pc = 0x62fe;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_62fe:
    /* 06:62fe */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x62ff;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62ff:
    /* 06:62ff */     /* NOP */
    ctx->pc = 0x6300;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6300:
    /* 06:6300 */     /* NOP */
    ctx->pc = 0x6301;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6301:
    /* 06:6301 */     /* NOP */
    ctx->pc = 0x6302;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6302:
    /* 06:6302 */     /* NOP */
    ctx->pc = 0x6303;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6303:
    /* 06:6303 */     /* NOP */
    ctx->pc = 0x6304;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6304:
    /* 06:6304 */     /* NOP */
    ctx->pc = 0x6305;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6305:
    /* 06:6305 */     /* NOP */
    ctx->pc = 0x6306;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6306:
    /* 06:6306 */     /* NOP */
    ctx->pc = 0x6307;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6307:
    /* 06:6307 */     /* NOP */
    ctx->pc = 0x6308;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $00 */
pc_6308:
    /* 06:6308 */     gb_cp8(ctx, 0x00);
    ctx->pc = 0x630a;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,A */
pc_630a:
    /* 06:630a */     ctx->a = ctx->a;
    ctx->pc = 0x630b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_630b:
    /* 06:630b */     /* NOP */
    ctx->pc = 0x630c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,A */
pc_630c:
    /* 06:630c */     ctx->a = ctx->a;
    ctx->pc = 0x630d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_630d:
    /* 06:630d */     /* NOP */
    ctx->pc = 0x630e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,A */
pc_630e:
    /* 06:630e */     ctx->a = ctx->a;
    ctx->pc = 0x630f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_630f:
    /* 06:630f */     /* NOP */
    ctx->pc = 0x6310;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_6310:
    /* 06:6310 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x6311;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6311:
    /* 06:6311 */     /* NOP */
    ctx->pc = 0x6312;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC SP */
pc_6312:
    /* 06:6312 */     gbrt_timed_dec16(ctx, &ctx->sp);
    ctx->pc = 0x6313;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6313:
    /* 06:6313 */     /* NOP */
    ctx->pc = 0x6314;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_6314:
    /* 06:6314 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x6315;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6315:
    /* 06:6315 */     /* NOP */
    ctx->pc = 0x6316;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC E */
pc_6316:
    /* 06:6316 */     ctx->e = gb_dec8(ctx, ctx->e);
    ctx->pc = 0x6317;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC C */
pc_6317:
    /* 06:6317 */     ctx->c = gb_inc8(ctx, ctx->c);
    ctx->pc = 0x6318;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6318:
    /* 06:6318 */     /* NOP */
    ctx->pc = 0x6319;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6319:
    /* 06:6319 */     /* NOP */
    ctx->pc = 0x631a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_631a:
    /* 06:631a */     /* NOP */
    ctx->pc = 0x631b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_631b:
    /* 06:631b */     /* NOP */
    ctx->pc = 0x631c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0f00 */
pc_631c:
    /* 06:631c */     ctx->bc = 0x0f00;
    ctx->pc = 0x631f;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_631f:
    /* 06:631f */     /* NOP */
    ctx->pc = 0x6320;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_6320:
    /* 06:6320 */     gbrt_timed_rst(ctx, 0x38, 0x6321);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6321:
    /* NOP */
    /* 06:6321 */     /* NOP */
    ctx->pc = 0x6322;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,A */
pc_6322:
    /* 06:6322 */     ctx->a = ctx->a;
    ctx->pc = 0x6323;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6323:
    /* 06:6323 */     /* NOP */
    ctx->pc = 0x6324;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP H */
pc_6324:
    /* 06:6324 */     gb_cp8(ctx, ctx->h);
    ctx->pc = 0x6325;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6325:
    /* 06:6325 */     /* NOP */
    ctx->pc = 0x6326;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_6326:
    /* 06:6326 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x6327;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_6327:
    /* 06:6327 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x6328;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6328:
    /* 06:6328 */     /* NOP */
    ctx->pc = 0x6329;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6329:
    /* 06:6329 */     /* NOP */
    ctx->pc = 0x632a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_632a:
    /* 06:632a */     /* NOP */
    ctx->pc = 0x632b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_632b:
    /* 06:632b */     /* NOP */
    ctx->pc = 0x632c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_632c:
    /* 06:632c */     gbrt_timed_rst(ctx, 0x38, 0x632d);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_632d:
    /* NOP */
    /* 06:632d */     /* NOP */
    ctx->pc = 0x632e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_632e:
    /* 06:632e */     gbrt_timed_rst(ctx, 0x38, 0x632f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_632f:
    /* NOP */
    /* 06:632f */     /* NOP */
    ctx->pc = 0x6330;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_6330:
    /* 06:6330 */     gbrt_timed_rst(ctx, 0x38, 0x6331);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6331:
    /* NOP */
    /* 06:6331 */     /* NOP */
    ctx->pc = 0x6332;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_6332:
    /* 06:6332 */     gbrt_timed_rst(ctx, 0x38, 0x6333);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6333:
    /* NOP */
    /* 06:6333 */     /* NOP */
    ctx->pc = 0x6334;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$00 */
pc_6334:
    /* 06:6334 */     ctx->e = 0x00;
    ctx->pc = 0x6336;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC A */
pc_6336:
    /* 06:6336 */     ctx->a = gb_inc8(ctx, ctx->a);
    ctx->pc = 0x6337;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6337:
    /* 06:6337 */     /* NOP */
    ctx->pc = 0x6338;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6338:
    /* 06:6338 */     /* NOP */
    ctx->pc = 0x6339;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6339:
    /* 06:6339 */     /* NOP */
    ctx->pc = 0x633a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_633a:
    /* 06:633a */     /* NOP */
    ctx->pc = 0x633b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_633b:
    /* 06:633b */     /* NOP */
    ctx->pc = 0x633c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0200 */
pc_633c:
    /* 06:633c */     ctx->bc = 0x0200;
    ctx->pc = 0x633f;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_633f:
    /* 06:633f */     /* NOP */
    ctx->pc = 0x6340;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_6340:
    /* 06:6340 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x6341;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0103 */
pc_6341:
    /* 06:6341 */     ctx->bc = 0x0103;
    ctx->pc = 0x6344;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0000 */
pc_6344:
    /* 06:6344 */     ctx->bc = 0x0000;
    ctx->pc = 0x6347;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6347:
    /* 06:6347 */     /* NOP */
    ctx->pc = 0x6348;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NC,1 */
pc_6348:
    /* 06:6348 */     if (!ctx->f_c) {
        gbrt_timed_jump(ctx, 0x634b, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_06_634b;
    } /* NC */
    gbrt_timed_jump(ctx, 0x634a, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_634a:
    /* LD SP,$fa78 */
    /* 06:634a */     ctx->sp = 0xfa78;
    ctx->pc = 0x634d;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,H */
pc_634d:
    /* 06:634d */     ctx->a = ctx->h;
    ctx->pc = 0x634e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x634e in bank 6 */
    return;
loc_06_634b:
    /* LD A,B */
    /* 06:634b */     ctx->a = ctx->b;
    ctx->pc = 0x634c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,($fc7c) */
pc_634c:
    /* 06:634c */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, 0xfc7c);
    gb_tick(ctx, 1);
    ctx->pc = 0x634f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL) */
pc_634f:
    /* 06:634f */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x6350;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_6350:
    /* 06:6350 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x6351;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL) */
pc_6351:
    /* 06:6351 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x6352;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_6352:
    /* 06:6352 */     gbrt_timed_rst(ctx, 0x38, 0x6353);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_6353:
    /* CCF */
    /* 06:6353 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x6354;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,A */
pc_6354:
    /* 06:6354 */     gb_sbc8(ctx, ctx->a);
    ctx->pc = 0x6355;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP A */
pc_6355:
    /* 06:6355 */     gb_cp8(ctx, ctx->a);
    ctx->pc = 0x6356;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP A */
pc_6356:
    /* 06:6356 */     gb_cp8(ctx, ctx->a);
    ctx->pc = 0x6357;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,A */
pc_6357:
    /* 06:6357 */     gb_sbc8(ctx, ctx->a);
    ctx->pc = 0x6358;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,A */
pc_6358:
    /* 06:6358 */     ctx->e = ctx->a;
    ctx->pc = 0x6359;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_6359:
    /* XOR A */
    /* 06:6359 */     gb_xor8(ctx, ctx->a);
    ctx->pc = 0x635a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_635a:
    /* 06:635a */     gb_rrca(ctx);
    ctx->pc = 0x635b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_635b:
    /* 06:635b */     gbrt_timed_rst(ctx, 0x38, 0x635c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_635c:
    /* RRCA */
    /* 06:635c */     gb_rrca(ctx);
    ctx->pc = 0x635d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_635d:
    /* 06:635d */     gbrt_timed_rst(ctx, 0x38, 0x635e);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_635e:
    /* ADD A,A */
    /* 06:635e */     gb_add8(ctx, ctx->a);
    ctx->pc = 0x635f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,A */
pc_635f:
    /* 06:635f */     ctx->a = ctx->a;
    ctx->pc = 0x6360;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,A */
pc_6360:
    /* 06:6360 */     ctx->b = ctx->a;
    ctx->pc = 0x6361;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_6361:
    /* 06:6361 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x6362;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND E */
pc_6362:
    /* 06:6362 */     gb_and8(ctx, ctx->e);
    ctx->pc = 0x6363;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRA */
pc_6363:
    /* 06:6363 */     gb_rra(ctx);
    ctx->pc = 0x6364;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x6364 in bank 6 */
    return;
}

void func_06_6296(GBContext* ctx) {
    body_06_6296(ctx);
}

void func_06_6359(GBContext* ctx) {
    body_06_6296(ctx);
}

/* Shared body at 06:62cd */
static void body_06_62cd(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x62cd: goto loc_06_62cd;
        case 0x62ce: goto pc_62ce;
        case 0x62cf: goto loc_06_62cf;
        case 0x62d0: goto pc_62d0;
        case 0x62d1: goto pc_62d1;
        case 0x62d2: goto pc_62d2;
        case 0x62d3: goto pc_62d3;
        case 0x62d4: goto pc_62d4;
        case 0x62d5: goto pc_62d5;
        case 0x62d6: goto loc_06_62d6;
        case 0x62d7: goto loc_06_62d7;
        case 0x62d9: goto pc_62d9;
        case 0x62da: goto pc_62da;
        case 0x62db: goto loc_06_62db;
        default: break;
    }

loc_06_62cd:
    /* NOP */
    /* 06:62cd */     /* NOP */
    ctx->pc = 0x62ce;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_62ce:
    /* 06:62ce */     gbrt_timed_rst(ctx, 0x38, 0x62cf);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_62cf:
    /* NOP */
    /* 06:62cf */     /* NOP */
    ctx->pc = 0x62d0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,H */
pc_62d0:
    /* 06:62d0 */     ctx->a = ctx->h;
    ctx->pc = 0x62d1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62d1:
    /* 06:62d1 */     /* NOP */
    ctx->pc = 0x62d2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC A */
pc_62d2:
    /* 06:62d2 */     ctx->a = gb_inc8(ctx, ctx->a);
    ctx->pc = 0x62d3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_62d3:
    /* 06:62d3 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x62d4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,(HL) */
pc_62d4:
    /* 06:62d4 */     gb_tick(ctx, 7);
    gb_sbc8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x62d5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NZ */
pc_62d5:
    /* 06:62d5 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x62d6, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_62d6:
    /* RST $08 */
    /* 06:62d6 */     gbrt_timed_rst(ctx, 0x8, 0x62d7);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_08(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_06_62d7:
    /* LDH ($FF00+$06),A */
    /* 06:62d7 */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_TMA, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x62d9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_62d9:
    /* 06:62d9 */     /* NOP */
    ctx->pc = 0x62da;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NZ */
pc_62da:
    /* 06:62da */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x62db, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_06_62db:
    /* NOP */
    /* 06:62db */     /* NOP */
    ctx->pc = 0x62dc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x62dc in bank 6 */
    return;
}

void func_06_62cd(GBContext* ctx) {
    body_06_62cd(ctx);
}

