/* Generated by gbrecomp from Yu-Gi-Oh! Dark Duel Stories (U) [C][!] */
#include "Yu_Gi_Oh__Dark_Duel_Stories__U___C_____internal.h"

/* Shared body at d5:4002 */
static void body_d5_4002(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4002: goto loc_d5_4002;
        case 0x4003: goto loc_d5_4003;
        default: break;
    }

loc_d5_4002:
    /* RST $38 */
    /* d5:4002 */     gbrt_timed_rst(ctx, 0x38, 0x4003);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_d5_4003:
    goto loc_d5_4003; /* fallthrough */
}

void func_d5_4002(GBContext* ctx) {
    body_d5_4002(ctx);
}

/* Shared body at d5:4004 */
static void body_d5_4004(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4004: goto loc_d5_4004;
        case 0x4005: goto loc_d5_4005;
        case 0x4007: goto pc_4007;
        case 0x4008: goto pc_4008;
        case 0x4009: goto pc_4009;
        case 0x400b: goto loc_d5_400b;
        case 0x400c: goto loc_d5_400c;
        case 0x400e: goto pc_400e;
        case 0x400f: goto loc_d5_400f;
        case 0x4010: goto pc_4010;
        case 0x4011: goto pc_4011;
        case 0x4012: goto pc_4012;
        case 0x4014: goto loc_d5_4014;
        case 0x4017: goto pc_4017;
        default: break;
    }

loc_d5_4004:
    /* LD A,A */
    /* d5:4004 */     ctx->a = ctx->a;
    ctx->pc = 0x4005;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_d5_4005:
    /* LDH ($FF00+$7f),A */
    /* d5:4005 */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_BASE + 0x7f, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4007;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,B */
pc_4007:
    /* d5:4007 */     ctx->b = ctx->b;
    if (gbrt_test_breakpoint_enabled) {
        ctx->pc = 0x4008;
        ctx->stopped = 1;
        return;
    }
    ctx->pc = 0x4008;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL-) */
pc_4008:
    /* d5:4008 */     ctx->a = gbrt_timed_hl_read_auto(ctx, -1);
    ctx->pc = 0x4009;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,4 */
pc_4009:
    /* d5:4009 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x400f, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_d5_400f;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x400b, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_d5_400b:
    /* RST $38 */
    /* d5:400b */     gbrt_timed_rst(ctx, 0x38, 0x400c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_d5_400c:
    /* LDH ($FF00+$42),A */
    /* d5:400c */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_SCY, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x400e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_400e:
    /* d5:400e */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x400f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_d5_400f:
    /* ADD HL,DE */
    /* d5:400f */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x4010;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND B */
pc_4010:
    /* d5:4010 */     gb_and8(ctx, ctx->b);
    ctx->pc = 0x4011;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC C */
pc_4011:
    /* d5:4011 */     ctx->c = gb_inc8(ctx, ctx->c);
    ctx->pc = 0x4012;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,4 */
pc_4012:
    /* d5:4012 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4018, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_d5_4018;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4014, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_d5_4014:
    /* LD A,($60e2) */
    /* d5:4014 */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, 0x60e2);
    gb_tick(ctx, 1);
    ctx->pc = 0x4017;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC E */
pc_4017:
    /* d5:4017 */     ctx->e = gb_dec8(ctx, ctx->e);
    ctx->pc = 0x4018;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_d5_4018:
    goto loc_d5_4018; /* fallthrough */
}

void func_d5_4004(GBContext* ctx) {
    body_d5_4004(ctx);
}

void func_d5_4005(GBContext* ctx) {
    body_d5_4004(ctx);
}

void func_d5_400c(GBContext* ctx) {
    body_d5_4004(ctx);
}

/* Shared body at d5:401b */
static void body_d5_401b(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x401b: goto loc_d5_401b;
        case 0x401c: goto loc_d5_401c;
        case 0x401d: goto pc_401d;
        case 0x401e: goto loc_d5_401e;
        case 0x4020: goto loc_d5_4020;
        case 0x4021: goto pc_4021;
        case 0x4022: goto pc_4022;
        case 0x4024: goto loc_d5_4024;
        case 0x4027: goto loc_d5_4027;
        case 0x4028: goto loc_d5_4028;
        case 0x4029: goto pc_4029;
        case 0x402a: goto pc_402a;
        default: break;
    }

loc_d5_401b:
    /* LD A,A */
    /* d5:401b */     ctx->a = ctx->a;
    ctx->pc = 0x401c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_d5_401c:
    /* LD E,E */
    /* d5:401c */     ctx->e = ctx->e;
    ctx->pc = 0x401d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_401d:
    /* d5:401d */     gbrt_timed_rst(ctx, 0x38, 0x401e);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_d5_401e:
    /* LD DE,$b5ff */
    /* d5:401e */     ctx->de = GB_ERAM_BASE + 0x15ff;
    ctx->pc = 0x4021;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4021:
    /* d5:4021 */     /* NOP */
    ctx->pc = 0x4022;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,4 */
pc_4022:
    /* d5:4022 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4028, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_d5_4028;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4024, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_d5_4024; /* fallthrough */
loc_d5_4020:
    /* OR L */
    /* d5:4020 */     gb_or8(ctx, ctx->l);
    ctx->pc = 0x4021;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* d5:4021 */     /* NOP */
    ctx->pc = 0x4022;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,4 */
    /* d5:4022 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4028, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_d5_4028;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4024, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_d5_4024:
    /* CALL C,$b26a */
    /* d5:4024 */     if (ctx->f_c) {
        gbrt_timed_call(ctx, 0xb26a, 0x4027);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        return;
    } /* C */
    gbrt_timed_jump(ctx, 0x4027, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_d5_4027:
    /* DEC (HL) */
    /* d5:4027 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x4028;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_d5_4028:
    /* EI */
    /* d5:4028 */     ctx->ime_pending = 1;
    ctx->pc = 0x4029;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR C */
pc_4029:
    /* d5:4029 */     gb_xor8(ctx, ctx->c);
    ctx->pc = 0x402a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC E */
pc_402a:
    /* d5:402a */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x402b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x402b in bank 213 */
    return;
}

void func_d5_401b(GBContext* ctx) {
    body_d5_401b(ctx);
}

void func_d5_401c(GBContext* ctx) {
    body_d5_401b(ctx);
}

void func_d5_4020(GBContext* ctx) {
    body_d5_401b(ctx);
}

/* Shared body at d5:4030 */
static void body_d5_4030(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4030: goto loc_d5_4030;
        case 0x4031: goto pc_4031;
        case 0x4032: goto loc_d5_4032;
        case 0x4033: goto loc_d5_4033;
        case 0x4035: goto loc_d5_4035;
        case 0x4036: goto loc_d5_4036;
        case 0x4037: goto pc_4037;
        case 0x4039: goto loc_d5_4039;
        case 0x403a: goto loc_d5_403a;
        case 0x403b: goto pc_403b;
        default: break;
    }

loc_d5_4030:
    /* LD H,B */
    /* d5:4030 */     ctx->h = ctx->b;
    ctx->pc = 0x4031;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,B */
pc_4031:
    /* d5:4031 */     ctx->b = ctx->b;
    if (gbrt_test_breakpoint_enabled) {
        ctx->pc = 0x4032;
        ctx->stopped = 1;
        return;
    }
    ctx->pc = 0x4032;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_d5_4032:
    /* RST $28 */
    /* d5:4032 */     gbrt_timed_rst(ctx, 0x28, 0x4033);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_28(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_d5_4033:
    /* JR NZ,4 */
    /* d5:4033 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4039, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_d5_4039;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4035, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_d5_4035:
    /* RST $38 */
    /* d5:4035 */     gbrt_timed_rst(ctx, 0x38, 0x4036);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_d5_4036:
    /* LD L,A */
    /* d5:4036 */     ctx->l = ctx->a;
    ctx->pc = 0x4037;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($ff05),SP */
pc_4037:
    /* d5:4037 */     gb_write16(ctx, GB_IO_TIMA, ctx->sp);
    ctx->pc = 0x403a;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_d5_403a; /* fallthrough */
loc_d5_4039:
    /* RST $38 */
    /* d5:4039 */     gbrt_timed_rst(ctx, 0x38, 0x403a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_d5_403a:
    /* CPL */
    /* d5:403a */     ctx->a = ~ctx->a; ctx->f_n = 1; ctx->f_h = 1;
    ctx->pc = 0x403b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,$ae */
pc_403b:
    /* d5:403b */     gb_sbc8(ctx, 0xae);
    ctx->pc = 0x403d;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x403d in bank 213 */
    return;
}

void func_d5_4030(GBContext* ctx) {
    body_d5_4030(ctx);
}

void func_d5_4032(GBContext* ctx) {
    body_d5_4030(ctx);
}

void func_d5_4035(GBContext* ctx) {
    body_d5_4030(ctx);
}

/* Shared body at d5:403e */
static void body_d5_403e(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x403e: goto loc_d5_403e;
        case 0x403f: goto pc_403f;
        case 0x4040: goto loc_d5_4040;
        case 0x4041: goto pc_4041;
        case 0x4042: goto pc_4042;
        case 0x4043: goto loc_d5_4043;
        case 0x4044: goto pc_4044;
        case 0x4045: goto pc_4045;
        case 0x4047: goto pc_4047;
        case 0x4048: goto loc_d5_4048;
        case 0x4049: goto loc_d5_4049;
        case 0x404c: goto pc_404c;
        case 0x404e: goto pc_404e;
        case 0x4050: goto pc_4050;
        case 0x4051: goto loc_d5_4051;
        default: break;
    }

loc_d5_403e:
    /* LD H,B */
    /* d5:403e */     ctx->h = ctx->b;
    ctx->pc = 0x403f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_403f:
    /* d5:403f */     gbrt_timed_rst(ctx, 0x38, 0x4040);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_d5_4040:
    /* LD A,A */
    /* d5:4040 */     ctx->a = ctx->a;
    ctx->pc = 0x4041;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP D */
pc_4041:
    /* d5:4041 */     gb_cp8(ctx, ctx->d);
    ctx->pc = 0x4042;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $18 */
pc_4042:
    /* d5:4042 */     gbrt_timed_rst(ctx, 0x18, 0x4043);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_18(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_d5_4043:
    /* LD H,C */
    /* d5:4043 */     ctx->h = ctx->c;
    ctx->pc = 0x4044;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_4044:
    /* d5:4044 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x4045;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$01 */
pc_4045:
    /* d5:4045 */     ctx->e = 0x01;
    ctx->pc = 0x4047;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_4047:
    /* d5:4047 */     gbrt_timed_rst(ctx, 0x38, 0x4048);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_d5_4048:
    /* RST $18 */
    /* d5:4048 */     gbrt_timed_rst(ctx, 0x18, 0x4049);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_18(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_d5_4049:
    /* LD DE,$0004 */
    /* d5:4049 */     ctx->de = 0x0004;
    ctx->pc = 0x404c;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH ($FF00+$03),A */
pc_404c:
    /* d5:404c */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_BASE + 0x03, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x404e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,$63 */
pc_404e:
    /* d5:404e */     gb_sbc8(ctx, 0x63);
    ctx->pc = 0x4050;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_4050:
    /* d5:4050 */     gbrt_timed_rst(ctx, 0x38, 0x4051);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_d5_4051:
    /* LD A,A */
    /* d5:4051 */     ctx->a = ctx->a;
    ctx->pc = 0x4052;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4052 in bank 213 */
    return;
}

void func_d5_403e(GBContext* ctx) {
    body_d5_403e(ctx);
}

void func_d5_4040(GBContext* ctx) {
    body_d5_403e(ctx);
}

void func_d5_4048(GBContext* ctx) {
    body_d5_403e(ctx);
}

