/* Generated by gbrecomp */
#ifndef Yu_Gi_Oh__Dark_Duel_Stories__U___C_____H
#define Yu_Gi_Oh__Dark_Duel_Stories__U___C_____H

#include "gbrt.h"

const GBConfig* Yu_Gi_Oh__Dark_Duel_Stories__U___C_____default_config(void);
void Yu_Gi_Oh__Dark_Duel_Stories__U___C_____run(GBContext* ctx);
void Yu_Gi_Oh__Dark_Duel_Stories__U___C_____init(GBContext* ctx);
void Yu_Gi_Oh__Dark_Duel_Stories__U___C_____init_with_rom(GBContext* ctx, const uint8_t* ext_rom_data, size_t ext_rom_size);
int Yu_Gi_Oh__Dark_Duel_Stories__U___C_____main(int argc, char* argv[]);

#endif
