/* Generated by gbrecomp from Yu-Gi-Oh! Dark Duel Stories (U) [C][!] */
#include "Yu_Gi_Oh__Dark_Duel_Stories__U___C_____internal.h"

void Yu_Gi_Oh__Dark_Duel_Stories__U___C_____dispatch_ff(GBContext* ctx, uint16_t addr, uint16_t bank) {
    switch (addr) {
        case 0xff80:
            switch (bank) {
                case 0: func_ff80(ctx); break;
                case 116: func_74_ff80(ctx); break;
                case 118: func_76_4103(ctx); break;
                case 119: func_77_6d61(ctx); break;
                case 124: func_7c_45a0(ctx); break;
                case 138: func_8a_ff80(ctx); break;
                case 147: func_93_5921(ctx); break;
                case 152: func_98_4c7e(ctx); break;
                case 153: func_99_ff80(ctx); break;
                case 156: func_9c_663f(ctx); break;
                case 163: func_a3_6c66(ctx); break;
                case 167: func_a7_ff80(ctx); break;
                case 172: func_ac_5fe8(ctx); break;
                case 176: func_b0_690d(ctx); break;
                case 187: func_bb_ff80(ctx); break;
                case 191: func_bf_60a1(ctx); break;
                default: gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_BANK_NOT_COMPILED, 16); break;
            }
            break;
        case 0xff81:
            switch (bank) {
                case 43: func_2b_ff81(ctx); break;
                case 139: func_8b_72c0(ctx); break;
                case 145: func_91_5780(ctx); break;
                case 164: func_a4_562a(ctx); break;
                case 184: func_b8_6050(ctx); break;
                case 189: func_bd_508f(ctx); break;
                default: gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_BANK_NOT_COMPILED, 6); break;
            }
            break;
        case 0xff82:
            switch (bank) {
                case 0: func_ff80(ctx); break;
                case 43: func_2b_ff81(ctx); break;
                case 116: func_74_ff80(ctx); break;
                case 118: func_76_4103(ctx); break;
                case 119: func_77_6d61(ctx); break;
                case 124: func_7c_5a5c(ctx); break;
                case 130: func_82_ff82(ctx); break;
                case 131: func_83_7b14(ctx); break;
                case 137: func_89_7262(ctx); break;
                case 138: func_8a_ff80(ctx); break;
                case 139: func_8b_72c0(ctx); break;
                case 145: func_91_5780(ctx); break;
                case 147: func_93_5921(ctx); break;
                case 152: func_98_4c7e(ctx); break;
                case 153: func_99_ff80(ctx); break;
                case 156: func_9c_663f(ctx); break;
                case 163: func_a3_6c66(ctx); break;
                case 164: func_a4_562a(ctx); break;
                case 167: func_a7_ff80(ctx); break;
                case 172: func_ac_5fe8(ctx); break;
                case 176: func_b0_7488(ctx); break;
                case 184: func_b8_6050(ctx); break;
                case 187: func_bb_ff80(ctx); break;
                case 189: func_bd_508f(ctx); break;
                case 191: func_bf_60a1(ctx); break;
                default: gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_BANK_NOT_COMPILED, 25); break;
            }
            break;
        case 0xff83:
            switch (bank) {
                case 122: func_7a_ff83(ctx); break;
                case 123: func_7b_ff83(ctx); break;
                case 149: func_95_ff83(ctx); break;
                case 158: func_9e_41d1(ctx); break;
                case 172: func_ac_73ff(ctx); break;
                case 174: func_ae_4830(ctx); break;
                case 188: func_bc_ff83(ctx); break;
                case 191: func_bf_ff83(ctx); break;
                default: gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_BANK_NOT_COMPILED, 8); break;
            }
            break;
        case 0xff84:
            switch (bank) {
                case 0: func_ff80(ctx); break;
                case 43: func_2b_ff81(ctx); break;
                case 116: func_74_ff80(ctx); break;
                case 118: func_76_ff84(ctx); break;
                case 119: func_77_6d61(ctx); break;
                case 122: func_7a_ff83(ctx); break;
                case 123: func_7b_ff83(ctx); break;
                case 124: func_7c_5a5c(ctx); break;
                case 128: func_80_ff84(ctx); break;
                case 130: func_82_ff82(ctx); break;
                case 131: func_83_7b14(ctx); break;
                case 137: func_89_7262(ctx); break;
                case 138: func_8a_ff80(ctx); break;
                case 139: func_8b_72c0(ctx); break;
                case 145: func_91_5780(ctx); break;
                case 147: func_93_5921(ctx); break;
                case 149: func_95_ff83(ctx); break;
                case 152: func_98_4c7e(ctx); break;
                case 153: func_99_ff80(ctx); break;
                case 156: func_9c_663f(ctx); break;
                case 158: func_9e_41d1(ctx); break;
                case 163: func_a3_6c66(ctx); break;
                case 164: func_a4_562a(ctx); break;
                case 167: func_a7_ff80(ctx); break;
                case 172: func_ac_73ff(ctx); break;
                case 174: func_ae_4830(ctx); break;
                case 176: func_b0_7488(ctx); break;
                case 177: func_b1_47ce(ctx); break;
                case 184: func_b8_6050(ctx); break;
                case 187: func_bb_ff80(ctx); break;
                case 188: func_bc_ff83(ctx); break;
                case 189: func_bd_508f(ctx); break;
                case 191: func_bf_ff83(ctx); break;
                default: gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_BANK_NOT_COMPILED, 33); break;
            }
            break;
        case 0xff85:
            func_c1_ff85(ctx); break;
        case 0xff86:
            switch (bank) {
                case 0: func_ff80(ctx); break;
                case 43: func_2b_ff81(ctx); break;
                case 116: func_74_ff80(ctx); break;
                case 118: func_76_ff84(ctx); break;
                case 119: func_77_6d61(ctx); break;
                case 122: func_7a_ff83(ctx); break;
                case 123: func_7b_ff83(ctx); break;
                case 124: func_7c_5a5c(ctx); break;
                case 128: func_80_ff84(ctx); break;
                case 130: func_82_ff82(ctx); break;
                case 131: func_83_7b14(ctx); break;
                case 137: func_89_7262(ctx); break;
                case 138: func_8a_ff80(ctx); break;
                case 139: func_8b_72c0(ctx); break;
                case 145: func_91_5780(ctx); break;
                case 147: func_93_5921(ctx); break;
                case 149: func_95_ff83(ctx); break;
                case 152: func_98_4c7e(ctx); break;
                case 153: func_99_ff80(ctx); break;
                case 156: func_9c_663f(ctx); break;
                case 158: func_9e_41d1(ctx); break;
                case 163: func_a3_6c66(ctx); break;
                case 164: func_a4_562a(ctx); break;
                case 167: func_a7_ff80(ctx); break;
                case 172: func_ac_ff86(ctx); break;
                case 174: func_ae_4830(ctx); break;
                case 176: func_b0_7488(ctx); break;
                case 177: func_b1_47ce(ctx); break;
                case 179: func_b3_7e66(ctx); break;
                case 180: func_b4_ff86(ctx); break;
                case 182: func_b6_6cac(ctx); break;
                case 183: func_b7_4e5c(ctx); break;
                case 184: func_b8_6050(ctx); break;
                case 187: func_bb_ff80(ctx); break;
                case 188: func_bc_ff83(ctx); break;
                case 189: func_bd_508f(ctx); break;
                case 191: func_bf_ff83(ctx); break;
                case 193: func_c1_ff87(ctx); break;
                default: gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_BANK_NOT_COMPILED, 38); break;
            }
            break;
        case 0xff87:
            switch (bank) {
                case 0: func_ff80(ctx); break;
                case 43: func_2b_ff81(ctx); break;
                case 116: func_74_ff80(ctx); break;
                case 118: func_76_ff84(ctx); break;
                case 119: func_77_6d61(ctx); break;
                case 122: func_7a_ff83(ctx); break;
                case 123: func_7b_ff83(ctx); break;
                case 124: func_7c_5a5c(ctx); break;
                case 128: func_80_ff84(ctx); break;
                case 130: func_82_ff82(ctx); break;
                case 131: func_83_7b14(ctx); break;
                case 137: func_89_7262(ctx); break;
                case 138: func_8a_ff80(ctx); break;
                case 139: func_8b_72c0(ctx); break;
                case 145: func_91_5780(ctx); break;
                case 147: func_93_5921(ctx); break;
                case 149: func_95_ff83(ctx); break;
                case 152: func_98_4c7e(ctx); break;
                case 153: func_99_ff80(ctx); break;
                case 156: func_9c_663f(ctx); break;
                case 158: func_9e_41d1(ctx); break;
                case 163: func_a3_6c66(ctx); break;
                case 164: func_a4_562a(ctx); break;
                case 167: func_a7_ff80(ctx); break;
                case 172: func_ac_ff86(ctx); break;
                case 174: func_ae_4830(ctx); break;
                case 176: func_b0_7488(ctx); break;
                case 177: func_b1_47ce(ctx); break;
                case 179: func_b3_7e66(ctx); break;
                case 180: func_b4_ff86(ctx); break;
                case 182: func_b6_6cac(ctx); break;
                case 183: func_b7_4e5c(ctx); break;
                case 184: func_b8_6050(ctx); break;
                case 187: func_bb_ff80(ctx); break;
                case 188: func_bc_ff83(ctx); break;
                case 189: func_bd_508f(ctx); break;
                case 191: func_bf_ff83(ctx); break;
                case 193: func_c1_ff87(ctx); break;
                default: gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_BANK_NOT_COMPILED, 38); break;
            }
            break;
        case 0xff88:
            func_bb_ff88(ctx); break;
        case 0xff89:
            switch (bank) {
                case 0: func_ff80(ctx); break;
                case 43: func_2b_ff81(ctx); break;
                case 116: func_74_ff80(ctx); break;
                case 118: func_76_ff84(ctx); break;
                case 119: func_77_6d61(ctx); break;
                case 122: func_7a_ff83(ctx); break;
                case 123: func_7b_ff83(ctx); break;
                case 124: func_7c_5a5c(ctx); break;
                case 127: func_7f_7e82(ctx); break;
                case 128: func_80_ff84(ctx); break;
                case 130: func_82_ff82(ctx); break;
                case 131: func_83_7b14(ctx); break;
                case 137: func_89_7262(ctx); break;
                case 138: func_8a_ff80(ctx); break;
                case 139: func_8b_72c0(ctx); break;
                case 145: func_91_5780(ctx); break;
                case 147: func_93_5921(ctx); break;
                case 149: func_95_ff83(ctx); break;
                case 152: func_98_4c7e(ctx); break;
                case 153: func_99_ff80(ctx); break;
                case 156: func_9c_663f(ctx); break;
                case 158: func_9e_41d1(ctx); break;
                case 163: func_a3_6c66(ctx); break;
                case 164: func_a4_562a(ctx); break;
                case 167: func_a7_ff80(ctx); break;
                case 168: func_a8_ff89(ctx); break;
                case 172: func_ac_ff86(ctx); break;
                case 174: func_ae_4830(ctx); break;
                case 176: func_b0_7488(ctx); break;
                case 177: func_b1_47ce(ctx); break;
                case 179: func_b3_7e66(ctx); break;
                case 180: func_b4_ff86(ctx); break;
                case 182: func_b6_6cac(ctx); break;
                case 183: func_b7_4e5c(ctx); break;
                case 184: func_b8_6050(ctx); break;
                case 187: func_bb_ff80(ctx); break;
                case 188: func_bc_ff83(ctx); break;
                case 189: func_bd_508f(ctx); break;
                case 191: func_bf_ff83(ctx); break;
                case 193: func_c1_ff87(ctx); break;
                default: gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_BANK_NOT_COMPILED, 40); break;
            }
            break;
        default: gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_ADDRESS_NOT_COMPILED, 0); break;
    }
}

