/* Generated by gbrecomp from Yu-Gi-Oh! Dark Duel Stories (U) [C][!] */
#include "Yu_Gi_Oh__Dark_Duel_Stories__U___C_____internal.h"

/* Shared body at e9:4000 */
static void body_e9_4000(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_e9_4000:
    /* JP HL */
    /* e9:4000 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_e9_4000(GBContext* ctx) {
    body_e9_4000(ctx);
}

